Modified CToken test
CToken test is modified to utilise the scale parameter for CToken
initialization. Though CToken test still fails due to :

     AttributeError: 'ComptrollerMock' object has no attribute 'address'